<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Polochon.Serilog</PackageId>
    <Description>Serilog logging integration for the Polochon kernel.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Polochon.Abstractions/Polochon.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

</Project>
