<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Polochon/Polochon.csproj" />
    <ProjectReference Include="../../src/Polochon.Serilog/Polochon.Serilog.csproj" />
    <ProjectReference Include="../../src/Polochon.Telemetry.OpenTelemetry/Polochon.Telemetry.OpenTelemetry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="OpenTelemetry.Exporter.InMemory" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

</Project>
