<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Polochon.Persistence.SqlServer</PackageId>
    <Description>SQL Server persistence integration for the Polochon kernel.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Polochon.Abstractions/Polochon.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
